### ISSUE TITLE
Create a command to hide tags & colors.

### ISSUE THREAD

**Issue by last2fall** [Hexer10/HexTags#14]
I dont know if this already exists and I just cant use the google, but please can this be made if its not already? I would really look forward to it.

Thank you very much in advance.

**Comment by Hexer10** [comment]
What do you mean?
Do you want a command like `sm_toggletags` that will enable/disable the tags for all the players?

**Comment by last2fall** [comment]
sm_toggletags for each person with tag. Hide/unhide tag whenever he wants.

Thank you:)

**Comment by Hexer10** [comment]
Gotcha

**Comment by z4cH3r** [comment]
@Hexer10 
is there a change you can add it?
last update was more than a year ago

**Comment by Hexer10** [comment]
I've added the new command `sm_hidetags` in https://github.com/Hexer10/HexTags/commit/601cf69391ca4240c96a809f877c9e3147737869 .
When run, the tags and the colors in the chat will stop displaying the the scoreboard tag will be removed. Need a some testing before pushing the build.

**Comment by Hexer10** [comment]
Pushed the tag https://github.com/Hexer10/HexTags/releases/tag/1.49 ,
I forgot to mention that right now that the tags after a map change or a player disconnect will be always re enabled.
