### ISSUE TITLE
Change in RankMe Version format

### ISSUE THREAD

**Issue by TandelK** [Hexer10/HexTags#15]
Instead of having RankMe Tag to show real rank in Chat and Score Board. One of my friend actually modified the plugin but has some real bug with RankMe . If you want i can share the private version with you to try. 

"ScoreTag" [Head Admin][{country}][{rank}] 
"ChatTag"  [Head Admin][{country}][{rank}]  
This basically shows in Score Tag and Chat Tag as [Head Admin][IN][Rank-20]

**Comment by Hexer10** [comment]
I could add also this kind of support for rankme, thanks for the idea

**Comment by TandelK** [comment]
One of my friend actually did the plugin but error.log gets a Spam of 

https://pastebin.com/yRXUH46j

**Comment by Hexer10** [comment]
Could you post the code?
Btw you should add an IsClientInGame before the IsFakeClient check

**Comment by Cruze03** [comment]
https://forums.alliedmods.net/showpost.php?p=2620802&postcount=126

**Comment by Cruze03** [comment]
Can you do it like this :(?

**Comment by Hexer10** [comment]
I'll push a build as soon as the update is tested

**Comment by Hexer10** [comment]
Also ATM it displays only the rankme points, need more time to make the rank working as well

**Comment by TandelK** [comment]
So where can we use the {rank} format exactly ? In the above version given by @Cruze03 it auto adds in ChatTags and you can select them in ScoreTag if you wanted them.

**Comment by Cruze03** [comment]
Use {rankme} tag i think

**Comment by TandelK** [comment]
that shows current number of points instead of Rank

**Comment by Hexer10** [comment]
Okay, with the https://github.com/Hexer10/HexTags/commit/364aab41ee9901c8a8c8c56c9312ddb5d04d48f8, the RankMe rank is also supported use `{rmPoints}` to display the points, and `{rmRank}` to display the current rank.
At the moment the rank is only update only on a mapchange / when a player quit and rejoins, I still have to figure a reliable way to make this working as soon as the rank is changed, tough I think the only way is to make several queries.

**Comment by TandelK** [comment]
@Cruze03 can you create a Fork and update and send him Pull request ?

**Comment by Hexer10** [comment]
Probably I'll add cvar that will update the tags on roundend.

**Comment by TandelK** [comment]
Yeah that will be great idea because people having issue with SQL stored in other location so effecting Read and Write a lot

**Comment by TandelK** [comment]
any update on this yet Hex
