### ISSUE TITLE
Colors not working

### ISSUE THREAD

**Issue by ToggleIP** [Hexer10/HexTags#16]
Hi,

I was wondering if i could get some help because the colors aren't working on my L4D2 server.

**Comment by ToggleIP** [comment]
I cannot see anny errors about hextags

**Comment by Hexer10** [comment]
Can you see the chat prefix tag?

**Comment by Hexer10** [comment]
Seems like it's related with #17

**Comment by ToggleIP** [comment]
Yes the tag is there
