### ISSUE TITLE
Don`t work colors

### ISSUE THREAD

**Issue by baferpro** [Hexer10/HexTags#17]
Game: CS:GO
Version: Last at the time of creation of the issue
When connect, when change team, Still does not paint.
It works only after writing sm_reloadtags... And so you need to write every time

**Comment by Hexer10** [comment]
Gonna check out, if it's an issue with the event that is currently being called, or with the plugin itself

**Comment by Hexer10** [comment]
Thanks for reporting! Just fixed.
I'm pushing an update soon.
