### ISSUE TITLE
Feature request Add hl_gangs support

### ISSUE THREAD

**Issue by baferpro** [Hexer10/HexTags#19]
Maybe add support https://github.com/Headline/Gangs
Example:
```"ScoreTag" "[{GangName}]"```
Example plugin: https://github.com/Headline/Gangs/blob/master/hl_gangs_clantags.sp

**Comment by Hexer10** [comment]
Added with https://github.com/Hexer10/HexTags/commit/ae722127687bfaa0b627938a49b59cf167aadaf8
But it isn't tested, I'm going to push an update as soon as I'm sure it works properly

**Comment by baferpro** [comment]
But do it, if there is no gang, then nothing is output or type without gang

**Comment by Hexer10** [comment]
So if he hasn't a gang what should I put, back space or some placeholder text?

**Comment by Hexer10** [comment]
I've ended up creating a new cvar: `sm_hextags_nogang` it you can test it, I'll be happy to push the build

**Comment by nanociaglia** [comment]
this is not working, the Gang's tags are appearing at the beginning of the round, but it disappear after a few seconds and the real tags using hextags.cfg appears. For example:

My real hextag: [OWNER]
My Gang: HelloWord

HelloWord is appearing first, after a few seconds, [OWNER] is appearing
