### ISSUE TITLE
hl_gangs support (replacement)

### ISSUE THREAD

**Issue by nanociaglia** [Hexer10/HexTags#21]
Due GitHub is more organized than discord, i want to suggest that i said before:

ScoreTag replacement when someone join in a gang. Let's think that i've the following ScoreTag (because i'm root)

    "@Owner"
	{
		"ScoreTag" "[OWNER]"
		"ChatTag"	"{red}[OWNER] "
		"ChatColor" "{grey}"
		"NameColor" "{green}"
    }

If i create/join in a gang called (for example): TheBestOnes, the ScoreTag [OWNER] still there. What i want is that the owner scoretag should be replaced for {gang} or something like that.
Thanks

**Comment by Hexer10** [comment]
Thanks for filing an issue in GitHub, most likely I'll add a selector that will target only players with a tag

**Comment by baferpro** [comment]
![image](https://user-images.githubusercontent.com/20227450/49744108-2e3b9a80-fcad-11e8-9864-f9f5bee595d1.png)
I have long been implemented for myself, but it is unlikely that I will give it to the public :3

**Comment by nanociaglia** [comment]
make it public lol

**Comment by Hexer10** [comment]
Gotta test this a little bit: https://github.com/Hexer10/HexTags/commit/f971ac36b423d7759fb3f64f159dd1c0dc6f7523 as soon as it's tested, I'll push the build.
Ideally this is what it should look like:
```
"HexTags"
{
	"@Owner"
	{
		"Gang"
		{
			"ScoreTag" "[{gang}]"
		}
		
		"ScoreTag" "[Owner]"
		"ChatTag" "[Owner]"
		"ChatColor" "red"
	}
}
```
So every player that is in the group owner will have the red chat color and the `[Owner]` *chat tag*, then if he's in a gang, it will have as tag his gang's name otherwise `[Owner]`

**Comment by nanociaglia** [comment]
PERFECT! Good job, and thank you!

**Comment by nanociaglia** [comment]
Tested, it isn't working..

**Comment by nanociaglia** [comment]
I've fixed it, change gl_gangs to hl_gangs
https://github.com/Hexer10/HexTags/blob/master/addons/sourcemod/scripting/hextags.sp#L143

**Comment by nanociaglia** [comment]
I've found a mistake, change gl_gangs to hl_gangs
https://github.com/Hexer10/HexTags/blob/master/addons/sourcemod/scripting/hextags.sp#L143

Now its working but not at all, i must type !reloadtags everytime when someone join or create a gang to see the ScoreTag

**Comment by Hexer10** [comment]
Please try to set `cv_bParseRoundEnd` to `1` this will update the tags when the round ends

**Comment by nanociaglia** [comment]
Anyway i've made this, so that cvar won't be needed

`#pragma semicolon 1
 
#include <sourcemod>
#include <sdktools>
#include <sdkhooks>
#include <cstrike>
 
#pragma newdecls required

public void OnPluginStart() 
{
	HookEvent("round_start", round_start);
}

public Action round_start(Event event, char[] name, bool dontBroadcast) 
{
	ServerCommand("es_delayed 6.5 sm_reloadtags");
}`

**Comment by nanociaglia** [comment]
es_delayed is another plugin like a "delay" so sm_reloadtags are executed every round start after 6.5 seconds
