### ISSUE TITLE
Default section not working after new update 

### ISSUE THREAD

**Issue by TandelK** [Hexer10/HexTags#23]
After the removal of Default section and implementing it directly in "HexTags" section , it does not seems to be working 

```
"HexTags"
{
	"ScoreTag"	"{country}"
	"ChatTag"	"{country}"
	"ChatColor"	"{default}"
	"NameColor"	"{default}"
	
	"z"
	{
		"ScoreTag"	"{country}|[Head Admin]"
		"ChatTag"	"{country}|{rmRank}|{red}[Head Admin]"
		"ChatColor"	"{purple}"
		"NameColor"	"{green}"
	}

}
```

The {default} color tag is actually from https://goo.gl/VgAHbK

**Comment by TandelK** [comment]
The z flag stuff is working for the admins

**Comment by BrandonMBurt154** [comment]
same for me

**Comment by TandelK** [comment]
@Hexer10 Can you please help people out with this default section, i think it was better to keep default section.
