### ISSUE TITLE
Unable to compile on 1.7.3 sourcemod

### ISSUE THREAD

**Issue by SpiritBob** [Hexer10/HexTags#25]
Chat-Processor compiles perfectly without any warnings or errors on Sourcemod 1.7.3

Could you please make it so this does too? The reason for the need to compile it is because the original release is using the latest (or one of the latest) sourcemod builds which utilize new Data types which simply old Sourcemod 1.7 does not. That causes the plugin to fail loading with the data type error

[SM] Plugin hextags.smx failed to load: Native "DataPack.Reset" was not found.

Chat-Processor had the same problem hence why I compiled it under 1.7 and now everything is a-okay!

Please fix this, as majority of competitive plugins in L4D2 are compiled under 1.7 or older! o7

**Comment by Hexer10** [comment]
You should just find the line where `DataPack.Reset` is placed and and replace it with the function `ResetPackPosition` iirc
