### ISSUE TITLE
Debug in chat

### ISSUE THREAD

**Issue by Skoodie** [Hexer10/HexTags#26]
Debug in chat

https://prnt.sc/n35nnv

 - Game [CSGO]
 - Sourcemod version 1.9.0.6275
 - Sourcemod plugins list https://hastebin.com/voniyecipe.css

**Comment by Hexer10** [comment]
Fixing this asap

**Comment by PolychromeSL** [comment]
Re-opening this to check if the latest version is fixed as it still printing debug to chat from the latest release available on GitHub:
![image](https://user-images.githubusercontent.com/32105705/61800055-b026a100-ae02-11e9-8a7e-ed53446ca8f8.png)

- Game: CSGO
- SM Version: SourceMod 1.9.0.6281
- Plugins: https://pastebin.com/yf4Yh8Wx
