### ISSUE TITLE
Error while loading Default Tags and other Console Error

### ISSUE THREAD

**Issue by TandelK** [Hexer10/HexTags#27]
Download the latest version of github repo and tried to compile it and than run it on the server with update version of players in old default section which is back. Players cache is still getting stored somewhere. 

I did have a "z" flag first so i got the tag of "z" flag as [OWNER] mentioned in hextags.cfg but i removed myself from admins.cfg with no flags or other information, this means it should now pick up default section tags but instead it gave me console error everytime i connected to the server regarding changing back to hextags default one to [OWNER] tag . I had the following error logs in my logs files. 

`L 03/27/2019 - 08:29:47: [SM] Exception reported: Native is not bound
>L 03/27/2019 - 08:29:47: [SM] Blaming: hextags.smx
>L 03/27/2019 - 08:29:47: [SM] Call stack trace:
>L 03/27/2019 - 08:29:47: [SM]   [1] MostActive_GetPlayTimeTotal
>L 03/27/2019 - 08:29:47: [SM]   [2] Line 699, \addons\sourcemod\scripting\hextags.sp::Select_Time
>L 03/27/2019 - 08:29:47: [SM]   [4] Call_Finish
>L 03/27/2019 - 08:29:47: [SM]   [5] Line 571, \addons\sourcemod\scripting\hextags.sp::LoadTags
>L 03/27/2019 - 08:29:47: [SM]   [6] Line 241, 
 addons\sourcemod\scripting\hextags.sp::OnClientCommandKeyValues
>L 03/27/2019 - 08:29:47: [SM] Exception reported: Handle 19b48 is invalid (error 4)
>L 03/27/2019 - 08:29:47: [SM] Blaming: hextags.smx
>L 03/27/2019 - 08:29:47: [SM] Call stack trace:
>L 03/27/2019 - 08:29:47: [SM]   [0] CloseHandle
>L 03/27/2019 - 08:29:47: [SM]   [1] Line 588, \addons\sourcemod\scripting\hextags.sp::LoadTags
>L 03/27/2019 - 08:29:47: [SM]   [2] Line 241, \addons\sourcemod\scripting\hextags.sp::OnClientCommandKeyValues
>L 03/27/2019 - 08:30:41: Error log file session closed.
`

**Comment by Hexer10** [comment]
Have you installed mostactive? (It's not a requirement, just wondering)

**Comment by TandelK** [comment]
No i have not installed mostactive.

**Comment by TandelK** [comment]
Any updates yet @Hexer10 ?

**Comment by TandelK** [comment]
This seems to be fixed in new update. Closing it
