### ISSUE TITLE
TAGS

### ISSUE THREAD

**Issue by xVENUS** [Hexer10/HexTags#29]
Hello i wanna ask how to make tag for counter terrorist? If terrorist are like this : 

	"Terrorist" //Terrorist -> Only players in the terrorist team will have these tags.
	{
		"ScoreTag" "[Terrorist]" //The scoreboard-tag
		"Force"	"0"				//Don't force the tag
	}

then ct will look how?

	"??????"
	{
		"ScoreTag" "[Counter Terrorist]" //The scoreboard-tag
		"Force"	"0"				//Don't force the tag
	}

**Comment by TandelK** [comment]
/getteam --> Returns the current team name.


Please read document carefully given in Alliedmodders Forums of this Plugin.

**Comment by Hexer10** [comment]
As @TandelK already stated, you shall use that command, however for csgo the counter-terrorist team is named `CT`.
