### ISSUE TITLE
Gameme problem

### ISSUE THREAD

**Issue by rajkodev** [Hexer10/HexTags#3]
Hello, until i installed this plugin and cp my gameme rank plugin doesnt print anything to chat (points, connect messages etc.)
Is there any fix for this?

**Comment by Hexer10** [comment]
Does the plugin work?
# What's your plugin version?

**Comment by rajkodev** [comment]
@Hexer10 Last one, everything works. Except gameme. :)

**Comment by Hexer10** [comment]
I noticed that chat-processor has an issue with gameMe, so till that will be fixed I cannot do anything.

**Comment by rajkodev** [comment]
Also, there is problem where players without tags use colors:

https://scontent.fbeg1-1.fna.fbcdn.net/v/t34.0-12/26996108_10210684102327313_624262210_n.jpg?oh=f304dab4b249c1a20e418aa199f9e69c&oe=5A5EECAA

**Comment by Hexer10** [comment]
I cannot see where's the issue?
