### ISSUE TITLE
Add TAGS & Colors option players can choose from

### ISSUE THREAD

**Issue by crashzk** [Hexer10/HexTags#42]
It would be interesting to put an option where the player can choose which TAG and Chat & TAG color they would like to use, something like this plugin: https://forums.alliedmods.net/showthread.php?t=299733

Even making it compatible with HexTags would be interesting.

That is, if the player wanted to use a TAG other than the ones that are set by default in HexTags, they typed `!tags` and opened a menu with the tags configured on it, and even to choose the color they want.

**Comment by Hexer10** [comment]
I'm implementing this, if I don't encounter any further issues I should be able to push the enhancement by the next week.

**Comment by Hexer10** [comment]
This was implemented some time ago, see the `sm_tagslist` (it requires `sm_hextags_enable_tagslist` to be set to `1`)
