### ISSUE TITLE
Tags not showing for RES slot

### ISSUE THREAD

**Issue by BrutalCSEjziponken** [Hexer10/HexTags#54]
Hi

Have an issue.

My VIP players dont have the scoreboard tag nor the chat tag.
They have the RES flag.

03 "Chat-Processor" (2.2.1) by Drixevel
07 "hextags" (1.4 by Hexah

L 01/23/2020 - 16:051: [chat-processor.smx] Message formats generated for game 'csgo'.
L 01/23/2020 - 16:051: [chat-processor.smx] Successfully hooked a SayText2 chat hook.

No error logs.

Config:

```
"HexTags"
{
"b"
{
"ChatTag" "[ADMIN]"
"ChatColor" "{bluegrey}"
"NameColor" "{lime}"
}

"a"
{
"ScoreTag" "[VIP]"
"ChatTag" "[VIP]"
"ChatColor" "{bluegrey}"
"NameColor" "{lime}"
}
}
```

Seems to be working fine on a different server running EXACT same plugins and version with same plugin settings...
Not sure whats causing this "bug/issue"..

**Comment by Hexer10** [comment]
If you type sm_reloadtags, do they show? Also try to update the plugin to the latest version which is 1.50
