### ISSUE TITLE
SteamID Tag Not Working

### ISSUE THREAD

**Issue by ColterD** [Hexer10/HexTags#59]
**Describe the bug**
Adding tags by SteamID not working

**To Reproduce**
Add your SteamID into hextags.cfg as a tag entry with any ChatTag

**Example**

```
"HexTags"
{

	"STEAM_0:1:11367919"
		{
    		    "ChatTag"     "Owner • "
		}

}
```

**System Details**
SM 1.10

**See Also**
[Another User Having Same Issue](https://forums.alliedmods.net/showpost.php?p=2690061&postcount=336)

**Comment by freakexeuLow** [comment]
Yeah, I tested it myself and had the same problem^^

**Comment by Hexer10** [comment]
I should be able to debug it tonight, and hopefully push a fix

**Comment by Hexer10** [comment]
Fixed with the latest commit, sorry for taking so long.
Get the latest version here: https://github.com/Hexer10/HexTags/releases/tag/2.02
