### ISSUE TITLE
Double Print of Player-Specific Competitive Color

### ISSUE THREAD

**Issue by luckykev** [Hexer10/HexTags#60]
When no string defined for `"NameColor"` is used, or when the `{teamcolor}` is used, it prints the player-specific competitive color (CSGO generated) dot a second time before their name, after the custom chat tag.

If I use any color other than `{teamcolor}`, it does not print it a second time.

Config examples which **do cause** the double print:

```
	"a" //a -> Only players with the a flag will have these tags.
	{
		"ScoreTag" "[VIP]" //The scoreboard-tag
		"ChatTag"	"[VIP] " //The chat-tag
		"ChatColor" "{default}" //The chat color
		"NameColor" "{teamcolor}" //The name color
	}
```
```
	"a" //a -> Only players with the a flag will have these tags.
	{
		"ScoreTag" "[VIP]" //The scoreboard-tag
		"ChatTag"	"[VIP] " //The chat-tag
		"ChatColor" "{default}" //The chat color
	}
```

Config example which **does not cause** the double print:

```
	"a" //a -> Only players with the a flag will have these tags.
	{
		"ScoreTag" "[VIP]" //The scoreboard-tag
		"ChatTag"	"[VIP] " //The chat-tag
		"ChatColor" "{default}" //The chat color
		"NameColor" "{gold}" //The name color
	}
```

I tried searching the .sp & incl files and couldn't find anything obvious, unfortunately.

I have the latest Sourcemod, Hextags, and Chat-Processor builds as of yesterday, 4/6/2020. I have deleted the `custom-chatcolors-cp` plugin.

I have no other chat processing or tag plugins installed.

**Comment by Hexer10** [comment]
This is a known issue but I've never open an issue.
If you don't put any value it still bugs since `{teamcolor}` is the default value. At the moment I don't know why it behaves like that, I guess it is a csgo issue

**Comment by luckykev** [comment]
@Hexer10 Thanks for the reply!

**Comment by crashzk** [comment]
@Hexer10 I think it might help.

https://github.com/drixevel-dev/chat-processor/issues/5

I believe it's some [Chat Processor](https://github.com/drixevel-dev/chat-processor) error

**Comment by crashzk** [comment]
News?
