### ISSUE TITLE
Some Flags doesnt work

### ISSUE THREAD

**Issue by prT05** [Hexer10/HexTags#62]
**Describe the bug**
Some flags doesnt work, and exists topicas on alliedmodders and they say the same! For example flag "a,g" work and z, but the flag b dont and the costums flags only work the "s"! Like we have 20 flags but only work 5

Not my topic but the same issue: https://forums.alliedmods.net/showthread.php?t=323062

**Comment by Hexer10** [comment]
Could you check if with this version they work?
https://github.com/Hexer10/HexTags/releases/tag/1.50

**Comment by Hexer10** [comment]
I was be able to reproduce this, for some reason the Section name because uppercase and then sourcemod is no longer able to parse the flag, gonna fix it
