### ISSUE TITLE
Mostactive ranks don't work

### ISSUE THREAD

**Issue by rlevet** [Hexer10/HexTags#63]
**Describe the bug**
Any rank with "#numbers" will not work

**To Reproduce**
Just met the requirements in playtime, and nothing will appear. Tada!!

**System Details**
 - OS: CentOS Linux 7
 - Game : CSGO
 - Sourcemod version (send `sm version` reply from *server* console.) : 1.10.0.6460
 - Sourcemod plugins list : https://pastebin.com/ac5cpXRF
 - Your hextags.cfg : https://pastebin.com/1LEQP7Ce

**Comment by Hexer10** [comment]
Could you check if with this version they work?
https://github.com/Hexer10/HexTags/releases/tag/1.50

**Comment by rlevet** [comment]
> Could you check if with this version they work?
> https://github.com/Hexer10/HexTags/releases/tag/1.50

I don’t have any test server right now and my server is always 15+ players, I don’t want to break everything

I don’t think I’ll be able to test

**Comment by rlevet** [comment]
> 
> 
> Could you check if with this version they work?
> https://github.com/Hexer10/HexTags/releases/tag/1.50

Ok so I did that on my test server, and in this version the tags appear but in reverse: players with less than 300s active time will get the tag when set to #300 and people that have more than 300s will not get it

**Comment by rlevet** [comment]
@Hexer10 please :3

**Comment by rlevet** [comment]
Well, for some reason now it works

**Comment by Hexer10** [comment]
Okay? Sorry btw I totally missed your comment... If that happens again  you can always contact me via Telegram or Discord

**Comment by rlevet** [comment]
From what I saw, recompiling fixed it for me. Now I'm not exactly sure why this didn't work
