### ISSUE TITLE
L 05/28/2020 - 13:23:31: [hextags.smx] Invalid id: 0//1|0

### ISSUE THREAD

**Issue by BrutalCSEjziponken** [Hexer10/HexTags#69]
L 05/28/2020 - 13:23:31: [hextags.smx] Invalid id: 0//1|0

I dont know what this means. Any ideas?

**Comment by Hexer10** [comment]
That can be ignored for the time being, it is only used with features such as the `sm_tagslist`, to save the tag between map changes.
Usually it happens if you edit the config with that enabled
