### ISSUE TITLE
Tags are being set on bots

### ISSUE THREAD

**Issue by penalte** [Hexer10/HexTags#74]
**Describe the bug**
Tags are being set on bots, i use bots in my servers when a player joins a empty server he gets a bot to play with, the only server that is bother me is my surf server which uses surftimer, i have disable surftimer chat processor and scoreboard tags so i can use hextags and the replay bots have custom tags that tells users if it is a map/cp/bonus replay.

**To Reproduce**
just using normaly.

** To Fix **
probably checkin !fakeclient then set the tags?

**Expected behavior**
Bots not having tags set by hextags.

thank you very much for this plugin.

PS: i could read the code and try to add those fakeclient check but i have no time if you could tell me where it is i can add it and make a pull request.

**Comment by Hexer10** [comment]
This is by design; instead of disable the tags on the bots, I'd rather make a new `selector` for users that may want to set custom tags on bots or human players

**Comment by Hexer10** [comment]
I just pushed a commit which add both "human" and "bot" selectors (you need to compile the latest version from this repository) and try to set the tags like this:
```
"HexTags"
{
  "human"
  {
     /* Tags go here*/
  }
}

```

**Comment by penalte** [comment]
wow you so fast thanks i will test it when i get home, will give feedback.

thank you

**Comment by Hexer10** [comment]
Have you had the opportunity to test this?

**Comment by penalte** [comment]
Yes it is working perfect, sorry for the delay,
i can even set a custom tag for bots in my others servers, thank you so much.
