### ISSUE TITLE
Add chain support

### ISSUE THREAD

**Issue by baferpro** [Hexer10/HexTags#8]
Example config:
hextags.cfg
```
"HexTags"
{
	"Default" //All player will have this tags
	{
		"ScoreTag" "[Player]" //The scoreboard-tag
	}
	"@Admin"
	{
		"ScoreTag" "[Admin]" //The scoreboard-tag
		"ChatTag"	"{red}[Admin]" //The chat-tag
	}
	"CT"
	{
		"ChatColor" "{default}" //The chat color
		"NameColor" "{blue}" //The name color
	}
	"Terrorist"
	{
		"ChatColor" "{default}" //The chat color
		"NameColor" "{red}" //The name color
	}
	"Spectator"
	{
		"ChatColor" "{default}" //The chat color
		"NameColor" "{purple}" //The name color
	}
}
```
When a simple player for T, then he will be like this:
`[Player] in scoreboard-tag and {red}{NICK}:{default}{TEXT} in chat`

Or when admin for CT, then he will be like this:
`[Admin] in scoreboard-tag and {red}[Admin]{blue}{NICK}:{default}{TEXT} in chat`

I hope you understand what I wanted to convey to you. :3

**Comment by baferpro** [comment]
I would like to make a color chat for different teams. But also that this applies to all the above groups.

**Comment by Hexer10** [comment]
even though it's been a bit since this request I was thinking to do something like this:
`"HexTags"
{
	"Terrorist"
	{
		"@Admin"
		{
		
		}
		"STEAM:1xx"
		{
		
		}
		//Default
		"ChatColors" "xx"
		...
	}

}`

**Comment by Hexer10** [comment]
tough I still need to find a way to properly parse all the sub trees

**Comment by Hexer10** [comment]
I'm sorry if this took a long time, in a few minutes I'll push an update that will add exactly this.

**Comment by Hexer10** [comment]
This feature seems to be working without any major errors, if there are some fell free to report!
