### ISSUE TITLE
console is spamming forcing back default one!

### ISSUE THREAD

**Issue by zyzz1989** [Hexer10/HexTags#80]
Hey! The console is spamming this to me
It happens every 5 sec
afraid it will crash my server
hope you can help me with this situation

L 16/01/2021 - 19:44:54: [hextags.smx] KennyC<659><STEAM_1:1:543899530><> was changed by an external plugin, forcing him back to the HexTags' default one!
L 16/01/2021 - 19:44:54: [hextags.smx] KennyC<659><STEAM_1:1:543899530><> was changed by an external plugin, forcing him back to the HexTags' default one!

**Comment by Hexer10** [comment]
Do you have other plugins that change the tags?
Also please *fill in the template* when creating a new issue, I'd need your `hextags.cfg`

**Comment by zyzz1989** [comment]
No i don't have other plugins with change tags only have hextags

**Comment by Hexer10** [comment]
Please send your config file

**Comment by zyzz1989** [comment]
// This file was auto-generated by SourceMod (v1.10.0.6492)
// ConVars for plugin "hextags.smx"


// Set to 1 to enable the sm_tagslist command.
// -
// Default: "0"
sm_hextags_enable_tagslist "0"

// Text to use if user has no tag - needs hl_gangs.
// -
// Default: ""
sm_hextags_nogang ""

// If 1 the tags will be reloaded even on round end - Suggested to be used with plugins like mostactive or rankme.
// -
// Default: "0"
sm_hextags_roundend "0"

// HexTags plugin version
// -
// Default: "2.03"
sm_hextags_version "2.03"

**Comment by Hexer10** [comment]
Not that one, the one in sourcemod/configs/hextags.cfg

**Comment by zyzz1989** [comment]
here you go :)

![image](https://user-images.githubusercontent.com/33705945/104820166-679f4680-5833-11eb-8370-c20d72d57896.png)

**Comment by Hexer10** [comment]
So, the error is happening there is a maximum length for the scoreboard tag (iirc it is 16 characters), so when the plugin compares the tags that the user actually have with the one in cfg they are different (you should be able to see that even in the cfg)

**Comment by zyzz1989** [comment]
thx you so much
