### ISSUE TITLE
color tag twice

### ISSUE THREAD

**Issue by SanjaySRocks** [Hexer10/HexTags#82]
**Describe the bug**
Why there is 2 color dots before and after the name.

**To Reproduce**
Simply install chat processor and hextags.

**Expected behavior**
It should not show those 2 color tags before and after name.

**Screenshots**
Attached

**System Details**
 - OS: Debian/Ubuntu
 - Game: CSGO
SourceMod 1.10.0.6502, by AlliedModders LLC
To see running plugins, type "sm plugins"
To see credits, type "sm credits"
Visit http://www.sourcemod.net/

 - Sourcemod plugins list
 I am using this plugin my basic pug server with no extra plugins.
![ApplicationFrameHost_ZXbbMw71Qz](https://user-images.githubusercontent.com/30376256/131718246-64d1e72a-cd19-49c4-95ae-617d872dcc07.png)

**Comment by strteamservidores** [comment]
https://github.com/yuv41/remove-chat-color-circles

**Comment by SanjaySRocks** [comment]
> https://github.com/yuv41/remove-chat-color-circles

worked!

cant we remove the second dot that would be better

**Comment by Hexer10** [comment]
Closing since this doesn't seem directly related to this plugin
