### ISSUE TITLE
L4D2 Minimal Color Support

### ISSUE THREAD

**Issue by nameonascreen** [Hexer10/HexTags#83]
Sorry for not following the bug report layout but i feel it isn't needed as this is more or less a question.

Not 100% sure if this is a bug or just a lack of l4d2's color pallete but essentially the only colors i've found to work on l4d2 are the "teamcolor" color's and i'm sure some other randomly absurd ones work but haven been yet to find them.

Basically just wondering if there's supposed to be more color options or not

**Comment by Hexer10** [comment]
I don't play L4D2, so I don't know which colors are available for that game, however the colors are not handle by this plugin but from the chat-processor.
