### ISSUE TITLE
Add rainbow & color chat for every 'param'

### ISSUE THREAD

**Issue by Hexer10** [Hexer10/HexTags#9]

**Comment by paulocrash** [comment]
The Rainbow color option does not work for TAG in chat, only for color chat.

I tested with version 1.47.

Would you have any predictions to fix this BUG?

@Hexer10

**Comment by Hexer10** [comment]
In the last months I've been a bit inactive, however I should be able to push an update for this by the next week

**Comment by RMMSecurity** [comment]
@Hexer10 any chance of an update?

Thanks!  🙂

**Comment by Hexer10** [comment]
With the latest commit and release https://github.com/Hexer10/HexTags/releases/tag/1.48 the {rainbow} color should work for every parameter, is in the name, chat tag, and chat colors, {random} still have some minor issues but it's not a priority.

Please reply here you experience any issue.
